# Generated by Django 3.0.6 on 2020-06-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20200615_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prize',
            field=models.FloatField(null=True),
        ),
    ]
