# Generated by Django 3.0.6 on 2020-06-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shipping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(null=True, verbose_name='Numer zamówienia'),
        ),
    ]
