# Generated by Django 3.0.6 on 2020-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200622_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ilość'),
        ),
    ]
