# Generated by Django 3.0.6 on 2020-06-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200622_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prize',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='Cena'),
        ),
    ]
